# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b993c04736fee9c6101f401fc60994fa630533511b345b00014e212da5aa5dfe984bd819f8c1ccce82dc7105dab6a544dd3a7e7f333d40bb707e7e3b22927fef

test:
  secret_key_base: 1f35eab04860ed9ea47a8d7ec3a4367d1bdc4e5f160e42ef63309cd0a0653290274a5be2407155343f5c5bf656d6e237c4f93ad27dddbcec08a96ad90f7f98d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
